/**
 * Vendor the webfonts into src/fonts/ and generate src/fonts.css.
 *
 * Self-hosted rather than linked from fonts.googleapis.com, because:
 *   - two render-blocking requests to a third party become zero
 *   - no FOUT/layout shift waiting on a CDN
 *   - the service worker can actually cache them, so an installed app has its
 *     type offline instead of falling back to Georgia
 *   - no third-party request to explain in a privacy policy
 *
 * Files land in src/fonts/ (not public/) so Vite hashes them, emits them, and
 * rewrites the url() with the /next-leap/ base automatically.
 *
 * Run from artifacts/next-leap:  pnpm run fonts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const APP = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(APP, 'src', 'fonts');

// A browser UA is required or Google serves ttf instead of woff2.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  // Variable, with the two custom axes requested explicitly so the SOFT/WONK
  // settings in index.css have something to act on.
  { css: 'Fraunces:opsz,wght,SOFT,WONK@9..144,600..700,0..100,0..1', slug: 'fraunces' },
  { css: 'Inter:wght@400..700', slug: 'inter' },
  { css: 'IBM+Plex+Mono:wght@500;600;700', slug: 'plex-mono' },
];

// Only latin and latin-ext are worth shipping here.
const KEEP = [
  { name: 'latin-ext', probe: 'U+0100' },
  { name: 'latin', probe: 'U+0000' },
];

async function get(url, asBuffer = false) {
  const res = await fetch(url, { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

mkdirSync(FONT_DIR, { recursive: true });
const blocks = [];

for (const family of FAMILIES) {
  const css = await get(
    `https://fonts.googleapis.com/css2?family=${family.css}&display=swap`,
  );

  // Google emits one @font-face per unicode subset, each preceded by a
  // /* subset */ comment.
  const faces = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi)];
  let kept = 0;

  for (const [, subset, face] of faces) {
    if (!KEEP.some(k => k.name === subset)) continue;
    const url = face.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;

    const weight = face.match(/font-weight:\s*([^;]+);/)?.[1].trim() ?? '400';
    const filename = `${family.slug}-${subset}.woff2`;
    writeFileSync(path.join(FONT_DIR, filename), await get(url, true));

    blocks.push(
      face
        .replace(/url\(https:[^)]+\)/, `url('./fonts/${filename}')`)
        .replace(/@font-face\s*\{/, '@font-face {\n  /* self-hosted */'),
    );
    kept++;
    console.log(`  ${filename.padEnd(30)} weight ${weight}`);
  }
  if (!kept) throw new Error(`no latin subset found for ${family.css}`);
}

writeFileSync(
  path.join(APP, 'src', 'fonts.css'),
  '/* GENERATED by scripts/fonts.mjs — do not edit. Run `pnpm run fonts`. */\n\n' +
    blocks.join('\n\n') +
    '\n',
);
console.log(`\nwrote src/fonts.css (${blocks.length} faces)`);
